### ISSUE TITLE
Can't insert into databases

### ISSUE THREAD

**Issue by AngelTs** [blkmaarx/php-blockchain-explorer#1]
PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to connect to http://username:password@XXXXXXXXXX:6332' in json-rpc-client.php:141

With other json-rpc api explorer I made connection without problem to my server

**Comment by blkmaarx** [comment]
It has not to do with the database, but with the daemon. It says the json rpc cannot connect to daemon. You have rpcallowip setup properly in daemon conf file?

I'm not sure what else to suggest. It's an old project this.

**Comment by AngelTs** [comment]
Thanks for your respond.Here are my steps:
1.Set my values for all in "config.php"
2.Upload to server
3.Create some db and use phpMyAdmin to import "_db-setup.sql"
4.Change three lines in "database.class.php" because of obsolete and deprecate functions:

4.1.
//		$db = mysql_connect(DATABASE_HOST, DATABASE_USER, DATABASE_PASS);
//		mysql_select_db(DATABASE_NAME);"
$db = @new mysqli(DATABASE_HOST, DATABASE_USER, DATABASE_PASS, DATABASE_NAME);

4.2.
//		$result = mysql_query($q,$db);
$result = $db->query($q);

4.3.
//			$returnKey = mysql_fetch_array(mysql_query("SELECT LAST_INSERT_ID()"));
$returnKey = mysql_fetch_array($db->query("SELECT LAST_INSERT_ID()"));

5.start in browser:
http://......./richlist.php
http://......./search.php
http://......./explorer.php
http://......./cron.php
http://......./config.php

6.Nothing happened and the four tables in Db are empty (no rows)
=>Where is my mistake?

**Comment by blkmaarx** [comment]
Well it looks like in the rpc it cannot send request "getblockhash 0".

Try in file classes/daemon.class.php to make $clientd public (line 9)
Make new php file in base directory,

<?php 
include('config.php');

$jsonrpc = new jsonRPCClient("http://".WALLET_RPC_USER.":".WALLET_RPC_PASS."@".WALLET_RPC_SERVER.":".WALLET_RPC_PORT."");
print_r($jsonrpc->getinfo());

Does it show reply with getinfo results?

**Comment by AngelTs** [comment]
change private to public in daemon.class.php
and make new file new.php with your content.
The error is the same:
[18-Nov-2017 11:03:33 UTC] PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to connect to http://username:password@18.216.219.60:6332' in /home/...//BlockExplorer2/classes/json-rpc-client.php:141
Stack trace:
#0 /home/.../BlockExplorer2/new.php(5): jsonRPCClient->__call('getinfo', Array)
#1 /home/.../BlockExplorer2/new.php(5): jsonRPCClient->getinfo()
#2 {main}
  thrown in /home/.../BlockExplorer2/classes/json-rpc-client.php on line 141

**Comment by blkmaarx** [comment]
Right, so this means that the jsonrpc library cannot connect to the server with the daemon. For the daemon you will probably have to add rpcallowip=ip.ip.ip (you can use wildcards), and then restart the daemon.. and make sure the server and port at 18.216.219.60:6332 are accessible.

**Comment by AngelTs** [comment]
I already made that, because on the same server, there are another jsop rpc block explorer which work perfect (connect without problem to seed node)

**Comment by blkmaarx** [comment]
I'm sorry. It seems then that without doubt the jsonrpc.php library is not working.

**Comment by AngelTs** [comment]
in this case if we use "easybitcoin.php" https://github.com/aceat64/EasyBitcoin-PHP/
to replace json-rpc-client.php?

**Comment by blkmaarx** [comment]
It would probably work, as it seems all the calls are made in the same way.

**Comment by AngelTs** [comment]
it work -> tested with new.php

**Comment by blkmaarx** [comment]
Great :) see if the rest works. This is a very old unmaintained project and I can tell you the way it loads data is very inefficient. It works ok for a while until the blockchain gets too big.

**Comment by AngelTs** [comment]
for the start is good, but still can't load data in db

**Comment by AngelTs** [comment]
I copied "easybitcoin.php in /classes dir
in "daemon.class.php" insert "require_once( 'easybitcoin.php' );" at the beggining
and changed
"new jsonRPCClient("http://".WALLET_RPC_USER.":".WALLET_RPC_PASS."@".WALLET_RPC_SERVER.":".WALLET_RPC_PORT."");"
with
"new Bitcoin( WALLET_RPC_USER, WALLET_RPC_PASS, WALLET_RPC_SERVER, WALLET_RPC_PORT );"
in three places.

and now connect but still not grab info

**Comment by blkmaarx** [comment]
It seems the entire mysql library is outdated. I think all of them are old. 

Ok so what works for me is this:

In database.class.php change these:

`mysql_fetch_array, mysql_fetch_row, mysql_fetch_assoc`

To 

`mysqli_fetch_array, mysqli_fetch_row, mysqli_fetch_assoc`

In cron.php comment out this line:

`(PHP_SAPI !== 'cli' || isset($_SERVER['HTTP_USER_AGENT'])) && die('This daemon can only run in CLI');`

Then in database import _db-setup.sql

Then open cron.php in browser. (or preferably perhaps via cli/ terminal). For me it works it populates database.

**Comment by AngelTs** [comment]
blkmaarx, thank you so much for your time, effort and production help. After your last corrections all works ok and as expected. I tested it successfully with my future coin.
Thank you so much again. Regards
